plugins {
  id 'java'
  id 'com.google.cloud.tools.jib'
}

sourceCompatibility = 1.8
targetCompatibility = 1.8

jib {
  from {
    image = 'localhost:5001/test-entrypoint-base'
  }
  to {
    image = 'localhost:5001/gradle-system-property-test'
  }
  container {
    mainClass = 'com.test.HelloWorld'
    args = ['arg1', 'arg2']
    // entrypointMode NOT specified - will use system property
  }
  allowInsecureRegistries = true
}
